### PR TITLE
Fix byte order detection for `np.uint8` and other types for which byte order is not defined.

### PR DESCRIPTION
**Pull request by KOLANICH**
Fixes: #154

### CODE REVIEW

**Comment by Narsil** [comment]
Hi @KOLANICH ,

Thanks for the fix.

Do you mind not changing the return type `|` seems like the correct return type for `_byteorder` so we would need to just do 

`if byteorder not in {'<', '|'|:`  to fix it instead.

In addition, I think adding a test is worth it.

I can take care of everything if you want.

**Comment by KOLANICH** [comment]
I was thinking about a better solution - just remove that function and replace it with `def is_endian_ok(dtype) -> bool:`. We currently don't support any endian except le and it is unlikely that anything except LE will be implemented in any new hardware. TBH IMHO only le endian makes sense because ints of different sizes are compatible to each other (wrt zero padding in MSBs) and because it is easier to deal with in software-implemented arythmetics. It was strange that BE got used in any hardware at all given its drawbacks, such a simple idea as LE seems to be uncopyrightable and unpatentable.

**Comment by KOLANICH** [comment]
and, BTW, feel free to do everything yourself.

**Comment by Narsil** [comment]
> def is_endian_ok(dtype) -> bool:. We 

Even better idea, I did just that !

**Comment by Narsil** [comment]
I had to create #160 since I can't commit to your branch unfortunately.

**Pull request closed without merging**
