### PR TITLE
[MINOR FIX] Fix markdown header

### PR DESCRIPTION
**Pull request by cakiki**
This time using `cargo-readme` :)

### CODE REVIEW

**Comment by Narsil** [comment]
You need `make doc`  (There are two README to update).

**Comment by cakiki** [comment]
That's odd; I did run `make doc`. I now tried running it again but that does not seem to change anything.

**Comment by Narsil** [comment]
Doesn't it modify the root level `README`?

**Comment by cakiki** [comment]
Silly me. It did initially but somehow I did not include it in the commit. Apologies!

**Review by Narsil — APPROVED** [review]
LGTM. Thanks for this !

**Pull request merged**
