### PR TITLE
Testing torch==1.10 (lowest available on transformers with `frombuffer`) too.

### PR DESCRIPTION
**Pull request by Narsil**

### CODE REVIEW

**Comment by thomasw21** [comment]
Is it normal that the CI doesn't run `Install Python` ?

**Comment by Narsil** [comment]
CI doesn't run when source files are not modified (actually the rust test themselves shouldn't be run either on PRs that don't modify source code.

**Review by thomasw21 — APPROVED** [review]
LGTM! I don't see anywhere any requirements file (except the dev one). Should we enforce minimum torch version somewhere in the codebase? Otherwhise it'll crash with the same error. Maybe in `torch.py`?

**Comment by Narsil** [comment]
Hmm neither `torch` nor `tensorflow` nor `jax` should be required (like `transformers`) therefore, no `requirements.txt`.

I could definitely add an error when using a too old version of `torch`.

**Comment by thomasw21** [comment]
>I could definitely add an error when using a too old version of torch.

Yeah that's what I meant actually. Not mandatory, but it's easier to understand if the error tell you "You're using torch 1.9. We only support >10" than "Attribute `from_buffer` doesn't exist in `torch`"

**Pull request merged**
