### PR TITLE
[MINOR FIX] Fix Markdown header

### PR DESCRIPTION
**Pull request by cakiki**

### CODE REVIEW

**Comment by Narsil** [comment]
Hi @cakiki thanks for this.

This will probably fail as we keep multiple doc files in sync do you mind modifying `safetensors/src/lib.rs` first ?
Then running
```
cargo install cargo-readme
make doc
```
That should update all the README.md

**Comment by cakiki** [comment]
Sure thing!

**Comment by cakiki** [comment]
Fixed in https://github.com/huggingface/safetensors/pull/28

**Comment by Narsil** [comment]
You know you can edit your PR :)

**Comment by cakiki** [comment]
I did not want to tempt the `git` gods :smile:

**Pull request closed without merging**
