### PR TITLE
Adding support for sending `torch.device(..)` and XLA devices.

### PR DESCRIPTION
**Pull request by Narsil**
# What does this PR do?

Fixes # (issue) or description of the problem this PR solves.

### CODE REVIEW

**Review by sgugger — APPROVED** [review]
Nice!
Note that if you start to go down that rabbit hole, you have intel XPUs and ascend NPUs to worry about ;-)

**Comment by Narsil** [comment]
Deeper it goes :).

There are ways to make this a bit more agnostic if there are too many devices thanks for the tip !

**Comment by Narsil** [comment]
I'll see the verdict if this helps on inferentia or not.

**Comment by michaelbenayoun** [comment]
I do not know if it helps for now, but I think it works. Do not have the bandwith to test it thoroughly right now.

**Pull request closed without merging**
